new try

diff --git a/.github/workflows/integrate.yaml b/.github/workflows/integrate.yaml
--- a/.github/workflows/integrate.yaml
+++ b/.github/workflows/integrate.yaml
@@ -34,8 +34,32 @@ jobs:
       - name: Build project
         run: npm run build
 
-      # Executes subsequent steps only if the previous step fails
-      - name: Handle build failure
-        if: ${{ failure() }}
-        run: |
-          curl -X POST --data-urlencode "payload={\"channel\": \"#github-notifications\", \"username\": \"webhookbot\", \"text\": \"This is posted to #github-notifications and comes from a bot named webhookbot.\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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
+  send_notification_to_slack:
+    name: Send notification to Slack
+    runs-on: ubuntu-22.04
+    if: always()
+    needs: [Build]
+
+    steps:
+      - run: |
+          successText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* completed successfully."
+          failureText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* failed."
+          cancelledText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* was cancelled.😥"
+          status="${{ (contains(needs.*.result, 'cancelled') && 'cancelled') || (contains(needs.*.result, 'failure') && 'failure') || 'success' }}"
+
+          if [ "$status" = 'success' ]; then
+          color='good'
+          text=$successText
+          elif [ "$status" = 'failure' ]; then
+          color='danger'
+          text=$failureText
+          elif [ "$status" = "cancelled" ]; then
+            color='warning'
+            text=$cancelledText
+          fi
+
+          echo "{attachments: [{text: \"$text\", color: \"$color\"}]}" | curl \
+            "${{ secrets.SLACK_WEBHOOK_URL }}" \
+            -X "POST" \
+            --header "Content-Type: application/json" \
+            --data-binary @-
